version: "3.0"

networks:
  my_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 30.10.11.0/16
          gateway: 30.10.11.1

volumes:
  redisdata:
  uploads:
  pgdata:
  

services:
  plane-redis:
    image: redis:6.2.7-alpine
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.2
    volumes:
      - redisdata:/data
 
  plane-minio:
    image: minio/minio
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.3
    command: server /export --console-address ":9090"
    volumes:
      - uploads:/export
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
 
  plane-db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.4
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.5
    volumes:
      - ./web:/app/web
    env_file:
      - ./web/.env
    depends_on:
      - api
      - worker

  space:
    build:
      context: .
      dockerfile: ./space/Dockerfile.dev
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.6
    volumes:
      - ./space:/app/space
    depends_on:
      - api
      - worker
      - web

  api:
    build:
      context: ./apiserver
      dockerfile: Dockerfile.dev
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.7
    volumes:
      - ./apiserver:/code
    # command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --settings=plane.settings.local"
    env_file:
      - ./apiserver/.env
    depends_on:
      - plane-db
      - plane-redis
  
  worker:
    build:
      context: ./apiserver
      dockerfile: Dockerfile.dev
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.8
    volumes:
      - ./apiserver:/code
    command: /bin/sh -c "celery -A plane worker -l info"
    env_file:
      - ./apiserver/.env
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    build:
      context: ./apiserver
      dockerfile: Dockerfile.dev
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.9
    volumes:
      - ./apiserver:/code
    command: /bin/sh -c "celery -A plane beat -l info"
    env_file:
      - ./apiserver/.env
    depends_on:
      - api
      - plane-db
      - plane-redis

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 30.10.11.10
    ports:
      - ${NGINX_PORT}:80
    env_file:
      - .env
    environment:
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
    depends_on:
      - web
      - api
      - space
